ALTER TYPE "VerificationPurpose" ADD VALUE 'PASSWORD_RESET';
ALTER TYPE "SecurityEventType" ADD VALUE 'PASSWORD_RESET_REQUESTED';
ALTER TYPE "SecurityEventType" ADD VALUE 'PASSWORD_RESET_COMPLETED';
ALTER TYPE "SecurityEventType" ADD VALUE 'PASSWORD_CHANGED';
ALTER TYPE "SecurityEventType" ADD VALUE 'LOGOUT_ALL';
ALTER TYPE "SecurityEventType" ADD VALUE 'DEVICE_REVOKED';
