ALTER TYPE "SecurityEventType" ADD VALUE 'PRODUCT_ACTIVATED';
ALTER TYPE "SecurityEventType" ADD VALUE 'PRODUCT_PAUSED';
ALTER TYPE "SecurityEventType" ADD VALUE 'PRODUCT_RESUMED';
ALTER TYPE "SecurityEventType" ADD VALUE 'PRODUCT_REMOVED';
