export function mapOrder(order: any) {
  return {
    orderCode: order.publicCode,
    seller: { slug: order.sellerProfile.slug, storeName: order.sellerProfile.storeName },
    currency: order.currency,
    subtotalAmountMinor: order.subtotalAmountMinor.toString(),
    discountAmountMinor: order.discountAmountMinor.toString(),
    platformFeeAmountMinor: order.platformFeeAmountMinor.toString(),
    totalAmountMinor: order.totalAmountMinor.toString(),
    status: order.status,
    paymentStatus: order.paymentStatus,
    fulfillmentStatus: order.fulfillmentStatus,
    disputeStatus: order.disputeStatus,
    version: order.version,
    expiresAt: order.expiresAt.toISOString(),
    cancelledAt: order.cancelledAt?.toISOString() ?? null,
    expiredAt: order.expiredAt?.toISOString() ?? null,
    createdAt: order.createdAt.toISOString(),
    updatedAt: order.updatedAt.toISOString(),
    items: order.items.map((item: any) => ({
      productSlug: item.productSlug,
      productTitle: item.productTitle,
      variantTitle: item.variantTitle,
      productType: item.productType,
      productModel: item.productModel,
      deliveryMode: item.deliveryMode,
      quantity: item.quantity,
      unitAmountMinor: item.unitAmountMinor.toString(),
      lineTotalAmountMinor: item.lineTotalAmountMinor.toString(),
      currency: item.currency,
      serviceEstimatedDelivery: item.serviceEstimatedDelivery,
      serviceBuyerRequirements: item.serviceBuyerRequirements,
    })),
  };
}
