/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendedorIndexRouteImport } from './routes/vendedor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendedorVendasRouteImport } from './routes/vendedor.vendas'
import { Route as VendedorFinanceiroRouteImport } from './routes/vendedor.financeiro'
import { Route as VendedorAvaliacoesRouteImport } from './routes/vendedor.avaliacoes'
import { Route as VendedorAnunciosRouteImport } from './routes/vendedor.anuncios'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as VendedorAnunciosNovoRouteImport } from './routes/vendedor.anuncios.novo'

const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorIndexRoute = VendedorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendedorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendedorVendasRoute = VendedorVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorFinanceiroRoute = VendedorFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorAvaliacoesRoute = VendedorAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorAnunciosRoute = VendedorAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => VendedorRoute,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorAnunciosNovoRoute = VendedorAnunciosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => VendedorAnunciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/carteira': typeof CarteiraRoute
  '/checkout': typeof CheckoutRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/vendedor': typeof VendedorRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vendedor/anuncios': typeof VendedorAnunciosRouteWithChildren
  '/vendedor/avaliacoes': typeof VendedorAvaliacoesRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/vendas': typeof VendedorVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/vendedor/anuncios/novo': typeof VendedorAnunciosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/carteira': typeof CarteiraRoute
  '/checkout': typeof CheckoutRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vendedor/anuncios': typeof VendedorAnunciosRouteWithChildren
  '/vendedor/avaliacoes': typeof VendedorAvaliacoesRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/vendas': typeof VendedorVendasRoute
  '/admin': typeof AdminIndexRoute
  '/vendedor': typeof VendedorIndexRoute
  '/vendedor/anuncios/novo': typeof VendedorAnunciosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/carteira': typeof CarteiraRoute
  '/checkout': typeof CheckoutRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/vendedor': typeof VendedorRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vendedor/anuncios': typeof VendedorAnunciosRouteWithChildren
  '/vendedor/avaliacoes': typeof VendedorAvaliacoesRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/vendas': typeof VendedorVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/vendedor/anuncios/novo': typeof VendedorAnunciosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/carrinho'
    | '/carteira'
    | '/checkout'
    | '/favoritos'
    | '/login'
    | '/mensagens'
    | '/pedidos'
    | '/perfil'
    | '/recuperar-senha'
    | '/vendedor'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/produto/$id'
    | '/vendedor/anuncios'
    | '/vendedor/avaliacoes'
    | '/vendedor/financeiro'
    | '/vendedor/vendas'
    | '/admin/'
    | '/vendedor/'
    | '/vendedor/anuncios/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/carteira'
    | '/checkout'
    | '/favoritos'
    | '/login'
    | '/mensagens'
    | '/pedidos'
    | '/perfil'
    | '/recuperar-senha'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/produto/$id'
    | '/vendedor/anuncios'
    | '/vendedor/avaliacoes'
    | '/vendedor/financeiro'
    | '/vendedor/vendas'
    | '/admin'
    | '/vendedor'
    | '/vendedor/anuncios/novo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/carrinho'
    | '/carteira'
    | '/checkout'
    | '/favoritos'
    | '/login'
    | '/mensagens'
    | '/pedidos'
    | '/perfil'
    | '/recuperar-senha'
    | '/vendedor'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/produto/$id'
    | '/vendedor/anuncios'
    | '/vendedor/avaliacoes'
    | '/vendedor/financeiro'
    | '/vendedor/vendas'
    | '/admin/'
    | '/vendedor/'
    | '/vendedor/anuncios/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CarteiraRoute: typeof CarteiraRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  MensagensRoute: typeof MensagensRoute
  PedidosRoute: typeof PedidosRoute
  PerfilRoute: typeof PerfilRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  VendedorRoute: typeof VendedorRouteWithChildren
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  LojaSlugRoute: typeof LojaSlugRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/': {
      id: '/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof VendedorIndexRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendedor/vendas': {
      id: '/vendedor/vendas'
      path: '/vendas'
      fullPath: '/vendedor/vendas'
      preLoaderRoute: typeof VendedorVendasRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/financeiro': {
      id: '/vendedor/financeiro'
      path: '/financeiro'
      fullPath: '/vendedor/financeiro'
      preLoaderRoute: typeof VendedorFinanceiroRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/avaliacoes': {
      id: '/vendedor/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/vendedor/avaliacoes'
      preLoaderRoute: typeof VendedorAvaliacoesRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/anuncios': {
      id: '/vendedor/anuncios'
      path: '/anuncios'
      fullPath: '/vendedor/anuncios'
      preLoaderRoute: typeof VendedorAnunciosRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/anuncios/novo': {
      id: '/vendedor/anuncios/novo'
      path: '/novo'
      fullPath: '/vendedor/anuncios/novo'
      preLoaderRoute: typeof VendedorAnunciosNovoRouteImport
      parentRoute: typeof VendedorAnunciosRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VendedorAnunciosRouteChildren {
  VendedorAnunciosNovoRoute: typeof VendedorAnunciosNovoRoute
}

const VendedorAnunciosRouteChildren: VendedorAnunciosRouteChildren = {
  VendedorAnunciosNovoRoute: VendedorAnunciosNovoRoute,
}

const VendedorAnunciosRouteWithChildren =
  VendedorAnunciosRoute._addFileChildren(VendedorAnunciosRouteChildren)

interface VendedorRouteChildren {
  VendedorAnunciosRoute: typeof VendedorAnunciosRouteWithChildren
  VendedorAvaliacoesRoute: typeof VendedorAvaliacoesRoute
  VendedorFinanceiroRoute: typeof VendedorFinanceiroRoute
  VendedorVendasRoute: typeof VendedorVendasRoute
  VendedorIndexRoute: typeof VendedorIndexRoute
}

const VendedorRouteChildren: VendedorRouteChildren = {
  VendedorAnunciosRoute: VendedorAnunciosRouteWithChildren,
  VendedorAvaliacoesRoute: VendedorAvaliacoesRoute,
  VendedorFinanceiroRoute: VendedorFinanceiroRoute,
  VendedorVendasRoute: VendedorVendasRoute,
  VendedorIndexRoute: VendedorIndexRoute,
}

const VendedorRouteWithChildren = VendedorRoute._addFileChildren(
  VendedorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CarteiraRoute: CarteiraRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  MensagensRoute: MensagensRoute,
  PedidosRoute: PedidosRoute,
  PerfilRoute: PerfilRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  VendedorRoute: VendedorRouteWithChildren,
  CategoriaSlugRoute: CategoriaSlugRoute,
  LojaSlugRoute: LojaSlugRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
