/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as TaxasRouteImport } from './routes/taxas'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LitPointsRouteImport } from './routes/lit-points'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendedorIndexRouteImport } from './routes/vendedor.index'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendedorVendasRouteImport } from './routes/vendedor.vendas'
import { Route as VendedorFinanceiroRouteImport } from './routes/vendedor.financeiro'
import { Route as VendedorAvaliacoesRouteImport } from './routes/vendedor.avaliacoes'
import { Route as VendedorAnunciosRouteImport } from './routes/vendedor.anuncios'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as PedidosIdRouteImport } from './routes/pedidos.$id'
import { Route as PagamentoIdRouteImport } from './routes/pagamento.$id'
import { Route as MensagensIdRouteImport } from './routes/mensagens.$id'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminVendedoresRouteImport } from './routes/admin.vendedores'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTransacoesRouteImport } from './routes/admin.transacoes'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminDisputasRouteImport } from './routes/admin.disputas'
import { Route as AdminDenunciasRouteImport } from './routes/admin.denuncias'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAnunciosRouteImport } from './routes/admin.anuncios'
import { Route as VendedorAnunciosIndexRouteImport } from './routes/vendedor.anuncios.index'
import { Route as VendedorAnunciosNovoRouteImport } from './routes/vendedor.anuncios.novo'

const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxasRoute = TaxasRouteImport.update({
  id: '/taxas',
  path: '/taxas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LitPointsRoute = LitPointsRouteImport.update({
  id: '/lit-points',
  path: '/lit-points',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorIndexRoute = VendedorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendedorRoute,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendedorVendasRoute = VendedorVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorFinanceiroRoute = VendedorFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorAvaliacoesRoute = VendedorAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorAnunciosRoute = VendedorAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => VendedorRoute,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PedidosRoute,
} as any)
const PagamentoIdRoute = PagamentoIdRouteImport.update({
  id: '/pagamento/$id',
  path: '/pagamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensIdRoute = MensagensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MensagensRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendedoresRoute = AdminVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransacoesRoute = AdminTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputasRoute = AdminDisputasRouteImport.update({
  id: '/disputas',
  path: '/disputas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const VendedorAnunciosIndexRoute = VendedorAnunciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendedorAnunciosRoute,
} as any)
const VendedorAnunciosNovoRoute = VendedorAnunciosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => VendedorAnunciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/carteira': typeof CarteiraRoute
  '/checkout': typeof CheckoutRoute
  '/favoritos': typeof FavoritosRoute
  '/lit-points': typeof LitPointsRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRouteWithChildren
  '/pedidos': typeof PedidosRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/taxas': typeof TaxasRoute
  '/vendedor': typeof VendedorRouteWithChildren
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/disputas': typeof AdminDisputasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/transacoes': typeof AdminTransacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/mensagens/$id': typeof MensagensIdRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vendedor/anuncios': typeof VendedorAnunciosRouteWithChildren
  '/vendedor/avaliacoes': typeof VendedorAvaliacoesRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/vendas': typeof VendedorVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/vendedor/anuncios/novo': typeof VendedorAnunciosNovoRoute
  '/vendedor/anuncios/': typeof VendedorAnunciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/carteira': typeof CarteiraRoute
  '/checkout': typeof CheckoutRoute
  '/favoritos': typeof FavoritosRoute
  '/lit-points': typeof LitPointsRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRouteWithChildren
  '/pedidos': typeof PedidosRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/taxas': typeof TaxasRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/disputas': typeof AdminDisputasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/transacoes': typeof AdminTransacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/mensagens/$id': typeof MensagensIdRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vendedor/avaliacoes': typeof VendedorAvaliacoesRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/vendas': typeof VendedorVendasRoute
  '/admin': typeof AdminIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/vendedor': typeof VendedorIndexRoute
  '/vendedor/anuncios/novo': typeof VendedorAnunciosNovoRoute
  '/vendedor/anuncios': typeof VendedorAnunciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/carteira': typeof CarteiraRoute
  '/checkout': typeof CheckoutRoute
  '/favoritos': typeof FavoritosRoute
  '/lit-points': typeof LitPointsRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRouteWithChildren
  '/pedidos': typeof PedidosRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/taxas': typeof TaxasRoute
  '/vendedor': typeof VendedorRouteWithChildren
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/disputas': typeof AdminDisputasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/transacoes': typeof AdminTransacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/mensagens/$id': typeof MensagensIdRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vendedor/anuncios': typeof VendedorAnunciosRouteWithChildren
  '/vendedor/avaliacoes': typeof VendedorAvaliacoesRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/vendas': typeof VendedorVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/vendedor/anuncios/novo': typeof VendedorAnunciosNovoRoute
  '/vendedor/anuncios/': typeof VendedorAnunciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/carteira'
    | '/checkout'
    | '/favoritos'
    | '/lit-points'
    | '/login'
    | '/mensagens'
    | '/pedidos'
    | '/recuperar-senha'
    | '/taxas'
    | '/vendedor'
    | '/admin/anuncios'
    | '/admin/configuracoes'
    | '/admin/denuncias'
    | '/admin/disputas'
    | '/admin/pedidos'
    | '/admin/transacoes'
    | '/admin/usuarios'
    | '/admin/vendedores'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/mensagens/$id'
    | '/pagamento/$id'
    | '/pedidos/$id'
    | '/produto/$id'
    | '/vendedor/anuncios'
    | '/vendedor/avaliacoes'
    | '/vendedor/financeiro'
    | '/vendedor/vendas'
    | '/admin/'
    | '/perfil/'
    | '/vendedor/'
    | '/vendedor/anuncios/novo'
    | '/vendedor/anuncios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/carteira'
    | '/checkout'
    | '/favoritos'
    | '/lit-points'
    | '/login'
    | '/mensagens'
    | '/pedidos'
    | '/recuperar-senha'
    | '/taxas'
    | '/admin/anuncios'
    | '/admin/configuracoes'
    | '/admin/denuncias'
    | '/admin/disputas'
    | '/admin/pedidos'
    | '/admin/transacoes'
    | '/admin/usuarios'
    | '/admin/vendedores'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/mensagens/$id'
    | '/pagamento/$id'
    | '/pedidos/$id'
    | '/produto/$id'
    | '/vendedor/avaliacoes'
    | '/vendedor/financeiro'
    | '/vendedor/vendas'
    | '/admin'
    | '/perfil'
    | '/vendedor'
    | '/vendedor/anuncios/novo'
    | '/vendedor/anuncios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/carteira'
    | '/checkout'
    | '/favoritos'
    | '/lit-points'
    | '/login'
    | '/mensagens'
    | '/pedidos'
    | '/recuperar-senha'
    | '/taxas'
    | '/vendedor'
    | '/admin/anuncios'
    | '/admin/configuracoes'
    | '/admin/denuncias'
    | '/admin/disputas'
    | '/admin/pedidos'
    | '/admin/transacoes'
    | '/admin/usuarios'
    | '/admin/vendedores'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/mensagens/$id'
    | '/pagamento/$id'
    | '/pedidos/$id'
    | '/produto/$id'
    | '/vendedor/anuncios'
    | '/vendedor/avaliacoes'
    | '/vendedor/financeiro'
    | '/vendedor/vendas'
    | '/admin/'
    | '/perfil/'
    | '/vendedor/'
    | '/vendedor/anuncios/novo'
    | '/vendedor/anuncios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CarteiraRoute: typeof CarteiraRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritosRoute: typeof FavoritosRoute
  LitPointsRoute: typeof LitPointsRoute
  LoginRoute: typeof LoginRoute
  MensagensRoute: typeof MensagensRouteWithChildren
  PedidosRoute: typeof PedidosRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  TaxasRoute: typeof TaxasRoute
  VendedorRoute: typeof VendedorRouteWithChildren
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PagamentoIdRoute: typeof PagamentoIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxas': {
      id: '/taxas'
      path: '/taxas'
      fullPath: '/taxas'
      preLoaderRoute: typeof TaxasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lit-points': {
      id: '/lit-points'
      path: '/lit-points'
      fullPath: '/lit-points'
      preLoaderRoute: typeof LitPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/': {
      id: '/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof VendedorIndexRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendedor/vendas': {
      id: '/vendedor/vendas'
      path: '/vendas'
      fullPath: '/vendedor/vendas'
      preLoaderRoute: typeof VendedorVendasRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/financeiro': {
      id: '/vendedor/financeiro'
      path: '/financeiro'
      fullPath: '/vendedor/financeiro'
      preLoaderRoute: typeof VendedorFinanceiroRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/avaliacoes': {
      id: '/vendedor/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/vendedor/avaliacoes'
      preLoaderRoute: typeof VendedorAvaliacoesRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/anuncios': {
      id: '/vendedor/anuncios'
      path: '/anuncios'
      fullPath: '/vendedor/anuncios'
      preLoaderRoute: typeof VendedorAnunciosRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof PedidosRoute
    }
    '/pagamento/$id': {
      id: '/pagamento/$id'
      path: '/pagamento/$id'
      fullPath: '/pagamento/$id'
      preLoaderRoute: typeof PagamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/$id': {
      id: '/mensagens/$id'
      path: '/$id'
      fullPath: '/mensagens/$id'
      preLoaderRoute: typeof MensagensIdRouteImport
      parentRoute: typeof MensagensRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendedores': {
      id: '/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AdminVendedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transacoes': {
      id: '/admin/transacoes'
      path: '/transacoes'
      fullPath: '/admin/transacoes'
      preLoaderRoute: typeof AdminTransacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputas': {
      id: '/admin/disputas'
      path: '/disputas'
      fullPath: '/admin/disputas'
      preLoaderRoute: typeof AdminDisputasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/denuncias': {
      id: '/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendedor/anuncios/': {
      id: '/vendedor/anuncios/'
      path: '/'
      fullPath: '/vendedor/anuncios/'
      preLoaderRoute: typeof VendedorAnunciosIndexRouteImport
      parentRoute: typeof VendedorAnunciosRoute
    }
    '/vendedor/anuncios/novo': {
      id: '/vendedor/anuncios/novo'
      path: '/novo'
      fullPath: '/vendedor/anuncios/novo'
      preLoaderRoute: typeof VendedorAnunciosNovoRouteImport
      parentRoute: typeof VendedorAnunciosRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDenunciasRoute: typeof AdminDenunciasRoute
  AdminDisputasRoute: typeof AdminDisputasRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminTransacoesRoute: typeof AdminTransacoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVendedoresRoute: typeof AdminVendedoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDenunciasRoute: AdminDenunciasRoute,
  AdminDisputasRoute: AdminDisputasRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminTransacoesRoute: AdminTransacoesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVendedoresRoute: AdminVendedoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MensagensRouteChildren {
  MensagensIdRoute: typeof MensagensIdRoute
}

const MensagensRouteChildren: MensagensRouteChildren = {
  MensagensIdRoute: MensagensIdRoute,
}

const MensagensRouteWithChildren = MensagensRoute._addFileChildren(
  MensagensRouteChildren,
)

interface PedidosRouteChildren {
  PedidosIdRoute: typeof PedidosIdRoute
}

const PedidosRouteChildren: PedidosRouteChildren = {
  PedidosIdRoute: PedidosIdRoute,
}

const PedidosRouteWithChildren =
  PedidosRoute._addFileChildren(PedidosRouteChildren)

interface VendedorAnunciosRouteChildren {
  VendedorAnunciosNovoRoute: typeof VendedorAnunciosNovoRoute
  VendedorAnunciosIndexRoute: typeof VendedorAnunciosIndexRoute
}

const VendedorAnunciosRouteChildren: VendedorAnunciosRouteChildren = {
  VendedorAnunciosNovoRoute: VendedorAnunciosNovoRoute,
  VendedorAnunciosIndexRoute: VendedorAnunciosIndexRoute,
}

const VendedorAnunciosRouteWithChildren =
  VendedorAnunciosRoute._addFileChildren(VendedorAnunciosRouteChildren)

interface VendedorRouteChildren {
  VendedorAnunciosRoute: typeof VendedorAnunciosRouteWithChildren
  VendedorAvaliacoesRoute: typeof VendedorAvaliacoesRoute
  VendedorFinanceiroRoute: typeof VendedorFinanceiroRoute
  VendedorVendasRoute: typeof VendedorVendasRoute
  VendedorIndexRoute: typeof VendedorIndexRoute
}

const VendedorRouteChildren: VendedorRouteChildren = {
  VendedorAnunciosRoute: VendedorAnunciosRouteWithChildren,
  VendedorAvaliacoesRoute: VendedorAvaliacoesRoute,
  VendedorFinanceiroRoute: VendedorFinanceiroRoute,
  VendedorVendasRoute: VendedorVendasRoute,
  VendedorIndexRoute: VendedorIndexRoute,
}

const VendedorRouteWithChildren = VendedorRoute._addFileChildren(
  VendedorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CarteiraRoute: CarteiraRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritosRoute: FavoritosRoute,
  LitPointsRoute: LitPointsRoute,
  LoginRoute: LoginRoute,
  MensagensRoute: MensagensRouteWithChildren,
  PedidosRoute: PedidosRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  TaxasRoute: TaxasRoute,
  VendedorRoute: VendedorRouteWithChildren,
  CategoriaSlugRoute: CategoriaSlugRoute,
  LojaSlugRoute: LojaSlugRoute,
  PagamentoIdRoute: PagamentoIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  PerfilIndexRoute: PerfilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
